name: Build JAR

on:
  push:
    branches: [ "LEI-123291" ]   # branch principal

permissions:
  contents: write   # permite fazer commit se quiseres no futuro

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn -B -ntp clean package

      # 👇 Este é o passo pedido no D5
      - name: Copy jar to root
        run: cp target/*.jar .

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
